CREATE TABLE IF NOT EXISTS images (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    FilePath TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS tags (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    ParentId INT NULL,
    TagName VARCHAR(255) NOT NULL,
    FOREIGN KEY (ParentId) REFERENCES tags(Id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS image_tags (
    ImageId INT,
    TagId INT,
    PRIMARY KEY (ImageId, TagId),
    FOREIGN KEY (ImageId) REFERENCES images(Id) ON DELETE CASCADE,
    FOREIGN KEY (TagId) REFERENCES tags(Id) ON DELETE CASCADE
);